#ifndef SRC_LED_H_
#define SRC_LED_H_

#define ONBOARD_LED_PIN 		GPIO_PIN_13
#define ONBOARD_LED_PORT 		GPIOC

#define LED_ON		HAL_GPIO_WritePin(ONBOARD_LED_PORT, ONBOARD_LED_PIN, GPIO_PIN_RESET)
#define LED_OFF		HAL_GPIO_WritePin(ONBOARD_LED_PORT, ONBOARD_LED_PIN, GPIO_PIN_SET)

#endif /* SRC_LED_H_ */
