#ifndef SRC_LED_H_
#define SRC_LED_H_

#define CONNECTED_LED_PIN 		GPIO_PIN_13
#define CONNECTED_LED_PORT 		GPIOC

#define CONNECTED_LED_ON		HAL_GPIO_WritePin(CONNECTED_LED_PORT, CONNECTED_LED_PIN, GPIO_PIN_RESET)
#define CONNECTED_LED_OFF		HAL_GPIO_WritePin(CONNECTED_LED_PORT, CONNECTED_LED_PIN, GPIO_PIN_SET)

#endif /* SRC_LED_H_ */
